### ISSUE TITLE
Create github release

### ISSUE THREAD

**Issue by allanbowe** [nostr-connect/nostrum#17]
It would be great if your build process could create an automatic github release of your apk (with SHA checksums)

This would enable auto-discover in tools such as Obtainium

fyi the android build is not currently available at all it seems, the expo link returns this:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: turtle-v2-artifacts/production/c0f35709-4281-4f0e-a2a1-d02f47d00bf9/80ba55f5-88eb-4596-9ea5-386f0f7a4808/application-c044bec4-014c-4ea7-b625-69c556a28155.apk</Details>
</Error>
```

**Comment by alexgleason** [comment]
The APK download is broken, so I agree.

**Comment by alexgleason** [comment]
I ended up building it myself. apk is here: https://media.gleasonator.com/5fee90597e52b32ab7537a19624ea621512ea3edafdf0108568fa9cbc9d559a3.apk
