### ISSUE TITLE
Access to Testflight

### ISSUE THREAD

**Issue by aleixisp** [nostr-connect/nostrum#18]
Any chance I can have an access to test the app in TestFlight?
Currently also integrating NIP-46 on my client and would really help me having access to a mobile app with such capabilities.

Thanks!

**Comment by tiero** [comment]
Hey @aleixisp the TF was expired, I uploaded the same build! Now you should be able to join

**Comment by manimejia** [comment]
Thank you! I've been looking forward to test this out for a new web client also!

Just added this app to my test flight. Testing with snort.social, but having trouble signing in. Do you suggest an existing client with better support for nip-46 (for testing)? What's the best method for sending app feedback?

**Comment by tiero** [comment]
I was not aware snort.social implemented nip46. Not aware of any of the major Nostr clients as of now

**Comment by manimejia** [comment]
Thank you for working in this. [NIP-46](https://maxgravitt.com/articles/nostr-connect-deep-dive/) has the potential to open up huge possibilities for nostr web apps, especially PWAs on mobile. Signer apps are the center of this. LMK how best I can support you in testing and building awareness for this app and other nip-46 integrations. 🫡

**Comment by badonyx** [comment]
I tried snort.social but could not get it working with Nostrum. Reported for continued discussion in #19.
