### ISSUE TITLE
Nostrum does not shows the Connect URI the first time

### ISSUE THREAD

**Issue by badonyx** [nostr-connect/nostrum#19]
Nostrum is the reference signer implementation for Nostr Connect. Is there also a reference client implementation?

The only implementation of Nostr Connect that I am aware of is in the mobile web app for [snort.social](https://snort.social/) but I was not able to get it working with Nostrum on iOS. When I copy and paste the code into Nostrum and press "Approve" nothing happens. Is it a problem with the client or the signer?

If there are other client implementations please share them here.

**Comment by tiero** [comment]
Did you checked the example client that uses the JavaScript SDK? There is also a live version linked in there 

https://github.com/nostr-connect/connect/tree/master/example

**Comment by badonyx** [comment]
Thanks. I tried the live demo by scanning the code with the iOS app and it does not seem to be working. It accepts the code but then it just goes back to the main screen still saying "Nothing yet" and the webpage still says "Disconnected".

**Comment by tiero** [comment]
Did you try again a second time to scan in the same session? For some reason, I also encountered a bug which scanning the QRCode the first time does not trigger the next step for some reason.

**Comment by manimejia** [comment]
Maybe @v0l has input?

**Comment by badonyx** [comment]
I tried scanning multiple times. It accepts the code and prompts to "Reject" or "Approve" for "example.com". Pressing "Approve" does nothing while pressing "Reject" dismisses the prompt.

**Comment by v0l** [comment]
I found this app to be very unreliable, so i wasnt able to test is completely, yes the NIP-46 button was removed in the new signup flow, you can see an old version of snort here which still has it: https://a842e4e1.snort-social.pages.dev/

**Comment by manimejia** [comment]
> I found this app to be very unreliable, so i wasnt able to test is completely

Thanks Kieran @v0l. Maybe with your assistance, @tiero will be able move forward implementing nip-46 on a working client in the wild? (Not much to play with in this space)

Y'all both smarter than me. All I know is that nip-46 native app is essential to the future of nostr PWAs. How can I help?

**Comment by tiero** [comment]
Apologies guys, bit busy moment for me now at work. Nostrum never meant to be production ready, but I must absolutely need to find the issue, be it on a relay, the app or the connect SDK. I will try to find time this weekend 🙏

**Comment by tiero** [comment]
It was a React state issue. It seems now to be fixed, let's on Testflight once it gets approved.

Feel free to test from master the latest commit on a deceive of yours

**Comment by tiero** [comment]
It seems to be fixed on the latest TestFlight, thanks for reporting.
